<?php

use PHPUnit\Framework\TestCase;
use WP_CLI_Build\Helper\Utils;

class Utils_Test extends TestCase
{

    private $mockupVersions = array(
        '5.0' => 'insecure',
        '5.0.1' => 'insecure',
        '5.0.2' => 'insecure',
        '5.0.3' => 'insecure',
        '5.0.4' => 'insecure',
        '5.0.6' => 'insecure',
        '5.0.7' => 'insecure',
        '5.0.8' => 'insecure',
        '5.0.9' => 'insecure',
        '5.0.10' => 'insecure',
        '5.0.11' => 'insecure',
        '5.0.12' => 'insecure',
        '5.0.13' => 'insecure',
        '5.0.14' => 'insecure',
        '5.1' => 'insecure',
        '5.1.1' => 'insecure',
        '5.1.2' => 'insecure',
        '5.1.3' => 'insecure',
        '5.1.4' => 'insecure',
        '5.1.5' => 'insecure',
        '5.1.6' => 'insecure',
        '5.1.7' => 'insecure',
        '5.1.8' => 'insecure',
        '5.1.9' => 'insecure',
        '5.1.10' => 'insecure',
        '5.1.11' => 'insecure',
        '5.2' => 'insecure',
        '5.2.1' => 'insecure',
        '5.2.2' => 'insecure',
        '5.2.3' => 'insecure',
        '5.2.4' => 'insecure',
        '5.2.5' => 'insecure',
        '5.2.6' => 'insecure',
        '5.2.7' => 'insecure',
        '5.2.8' => 'insecure',
        '5.2.9' => 'insecure',
        '5.2.10' => 'insecure',
        '5.2.11' => 'insecure',
        '5.2.12' => 'insecure',
        '5.2.13' => 'insecure',
        '5.3' => 'insecure',
        '5.3.1' => 'insecure',
        '5.3.2' => 'insecure',
        '5.3.3' => 'insecure',
        '5.3.4' => 'insecure',
        '5.3.5' => 'insecure',
        '5.3.6' => 'insecure',
        '5.3.7' => 'insecure',
        '5.3.8' => 'insecure',
        '5.3.9' => 'insecure',
        '5.3.10' => 'insecure',
        '5.4' => 'insecure',
        '5.4.1' => 'insecure',
        '5.4.2' => 'insecure',
        '5.4.3' => 'insecure',
        '5.4.4' => 'insecure',
        '5.4.5' => 'insecure',
        '5.4.6' => 'insecure',
        '5.4.7' => 'insecure',
        '5.4.8' => 'insecure',
        '5.5' => 'insecure',
        '5.5.1' => 'insecure',
        '5.5.2' => 'insecure',
        '5.5.3' => 'insecure',
        '5.5.4' => 'insecure',
        '5.5.5' => 'insecure',
        '5.5.6' => 'insecure',
        '5.5.7' => 'insecure',
        '5.6' => 'insecure',
        '5.6.1' => 'insecure',
        '5.6.2' => 'insecure',
        '5.6.3' => 'insecure',
        '5.6.4' => 'insecure',
        '5.6.5' => 'insecure',
        '5.6.6' => 'insecure',
        '5.7' => 'insecure',
        '5.7.1' => 'insecure',
        '5.7.2' => 'insecure',
        '5.7.3' => 'insecure',
        '5.7.4' => 'insecure',
        '5.8' => 'insecure',
        '5.8.1' => 'insecure',
        '5.8.2' => 'insecure',
        '3.7.37' => 'outdated',
        '3.8.37' => 'outdated',
        '3.9.35' => 'outdated',
        '4.0.34' => 'outdated',
        '4.1.34' => 'outdated',
        '4.2.31' => 'outdated',
        '4.3.27' => 'outdated',
        '4.4.26' => 'outdated',
        '4.5.25' => 'outdated',
        '4.6.22' => 'outdated',
        '4.7.22' => 'outdated',
        '4.8.18' => 'outdated',
        '4.9.19' => 'outdated',
        '5.0.15' => 'outdated',
        '5.1.12' => 'outdated',
        '5.2.14' => 'outdated',
        '5.3.11' => 'outdated',
        '5.4.9' => 'outdated',
        '5.5.8' => 'outdated',
        '5.6.7' => 'outdated',
        '5.7.5' => 'outdated',
        '5.8.3' => 'outdated',
        '5.9' => 'latest',
    );

    public function testShouldReturnCorrectDetermineCoreVersion(): void
    {
        $determine_core_version = Utils::determine_core_version($this->mockupVersions, '5.0');
        $this->assertEquals('5.0', $determine_core_version);
        $this->assertIsString($determine_core_version);
    }
}
